"""boss-mcp as something Claude Code can execute, on a runtime we control.

Claude Code starts the Boss's MCP server by running a command from the
session's MCP config. That command must be an absolute path to something
that works on a machine that has never seen pip, npm, or our repo's
virtualenv - and must never be the user's system Python.

There is no .app bundle to ship a binary in yet, so the helper is a
generated launcher at <home>/boss/bin/boss-mcp that re-enters the same
managed runtime the product itself runs on: uv's own CPython, the MCP
SDK pinned, our code on the path. Absolute paths throughout, resolved
when the launcher is written. When the app is bundled, the launcher's
body changes to exec the bundled runtime; nothing that calls it does.

Verification is not optional: `boss-mcp --version` must run and report
the protocol version the Conductor speaks, or the Boss is not started.
That is the difference between "the Boss has its tools" and "hope".
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .boss_tools import PROTOCOL_VERSION, REQUIRED_TOOLS

MCP_PIN = "mcp>=2,<3"
PYTHON_PIN = "3.13"


def find_uv() -> str | None:
    """The same resolution conduct.sh uses: the user's uv, then $PATH."""
    candidate = Path.home() / ".local" / "bin" / "uv"
    if candidate.exists():
        return str(candidate)
    return shutil.which("uv")


def launcher_text(uv: str, repo_root: Path) -> str:
    return (
        "#!/bin/bash\n"
        "# boss-mcp: the Boss's orchestration tools, as an MCP server.\n"
        "# Generated by the Voice Conductor; do not edit. Runs on uv's\n"
        "# managed Python, never the system one.\n"
        f'exec "{uv}" run --python-preference only-managed '
        f'--python {PYTHON_PIN} --with "{MCP_PIN}" --quiet '
        f'python -c "import sys; sys.path.insert(0, {str(repo_root)!r}); '
        'from conductor.boss_mcp import main; sys.exit(main())" "$@"\n'
    )


def ensure_helper(home: str | Path, repo_root: str | Path,
                  uv: str | None = None) -> Path:
    """Write (or refresh) the launcher and return its absolute path."""
    uv = uv or find_uv()
    if not uv:
        raise RuntimeError("uv is not installed, so boss-mcp cannot run: "
                           "install it from https://astral.sh/uv")
    path = Path(home) / "boss" / "bin" / "boss-mcp"
    path.parent.mkdir(parents=True, exist_ok=True)
    text = launcher_text(uv, Path(repo_root).resolve())
    if not path.exists() or path.read_text() != text:
        path.write_text(text)
    path.chmod(0o755)
    return path.resolve()


@dataclass
class HelperCheck:
    path: str
    ok: bool
    protocol: int | None = None
    problem: str = ""


def verify_helper(path: str | Path, timeout: float = 60.0) -> HelperCheck:
    """Run `boss-mcp --version` and compare protocol versions."""
    path = str(path)
    if not os.access(path, os.X_OK):
        return HelperCheck(path, False, problem="boss-mcp is not executable")
    try:
        done = subprocess.run([path, "--version"], capture_output=True,
                              text=True, timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        return HelperCheck(path, False, problem=f"boss-mcp did not start: {exc}")
    text = (done.stdout + done.stderr).strip()
    if done.returncode != 0:
        return HelperCheck(path, False,
                           problem=f"boss-mcp --version failed: {text[-300:]}")
    try:
        reported = int(text.split()[-1])
    except (ValueError, IndexError):
        return HelperCheck(path, False,
                           problem=f"boss-mcp reported no protocol version: {text[-120:]}")
    if reported != PROTOCOL_VERSION:
        return HelperCheck(path, False, protocol=reported,
                           problem=f"Boss tooling incompatible: helper speaks "
                                   f"protocol {reported}, this build expects "
                                   f"{PROTOCOL_VERSION}")
    return HelperCheck(path, True, protocol=reported)


def main(argv: list[str] | None = None) -> int:
    """`python -m conductor.boss_helper --check`: what CI and a release
    run. Non-zero when the helper is missing, cannot start, speaks the
    wrong protocol, or would not offer a required tool."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--home", default=str(Path.home() / ".voice-conductor"))
    parser.add_argument("--repo", default=str(Path(__file__).resolve().parent.parent))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    path = ensure_helper(args.home, args.repo)
    print(f"boss-mcp: {path}")
    check = verify_helper(path)
    if not check.ok:
        print(f"FAIL: {check.problem}", file=sys.stderr)
        return 2
    print(f"protocol: {check.protocol}")
    if args.check:
        done = subprocess.run([str(path), "--socket", "/nonexistent", "--list"],
                              capture_output=True, text=True, timeout=120)
        offered = {line.split('"name": "')[1].split('"')[0]
                   for line in done.stdout.splitlines() if '"name"' in line}
        missing = [t for t in REQUIRED_TOOLS if t not in offered]
        if missing:
            print(f"FAIL: required tools not offered: {missing}", file=sys.stderr)
            return 2
        print(f"tools: {len(offered)} offered, all {len(REQUIRED_TOOLS)} required present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
